### ISSUE TITLE
Rocket 0.5 was HTTP/2 support

### ISSUE THREAD

**Issue by williamdes** [flosse/rust-web-framework-comparison#128]
https://github.com/SergioBenitez/Rocket/releases/tag/v0.5.0-rc.1

Confirmed to work using: `curl --http2 http://127.0.0.1:8000/`

**Comment by flosse** [comment]
:+1: would you mind to open a PR?

**Comment by williamdes** [comment]
>  would you mind to open a PR?

I would prefer you to commit the change for me if you do not mind :)

**Comment by williamdes** [comment]
Done in 1150d612b998d0357c44ca4c5bfa8a59cee1f763
