### ISSUE TITLE
Real world app using Rocket

### ISSUE THREAD

**Issue by williamdes** [flosse/rust-web-framework-comparison#129]
[Vaultwarden](https://github.com/dani-garcia/vaultwarden#readme) !

A back-end for Bitwarden, written in Rust

Proof: https://github.com/dani-garcia/vaultwarden/blob/5772836be524117085970d338631137aa2ff1f0c/Cargo.toml#L31
Works: perfectly

**Comment by flosse** [comment]
?

**Comment by williamdes** [comment]
To add to: https://github.com/flosse/rust-web-framework-comparison#real-world-web-projects-using-rust
