### ISSUE TITLE
Percy is not outdated

### ISSUE THREAD

**Issue by AlephAlpha** [flosse/rust-web-framework-comparison#132]
https://github.com/chinedufn/percy

The last commit is yesterday.

**Comment by flosse** [comment]
Ah.. good to know, thx!

Unfortunately there still is no release / published crates :(

**Comment by AlephAlpha** [comment]
It seems that percy is split into many crates: [percy-dom](https://crates.io/crates/percy-dom), [percy-css](https://crates.io/crates/percy-css), [percy-router](https://crates.io/crates/percy-router), etc.

**Comment by flosse** [comment]
ok, it's now back again.
