### ISSUE TITLE
Rouille is not outdated

### ISSUE THREAD

**Issue by ravenexp** [flosse/rust-web-framework-comparison#134]
The last release 3.3.0 was 12 days ago.

It also seems to be the only framework in the list that is based on `tiny-http` and is mentioned in the tiny-http crate [`README`](https://github.com/tiny-http/tiny-http/blob/master/README.md#examples).

There are very few non-async web frameworks still going forward these days, so I think it deserves a mention.

**Comment by tazjin** [comment]
I just stumbled upon this list, immediately searched for `rouille` (which I use all the time, and which had a release less than 3 weeks ago) and was surprised to find it marked as outdated. Going to propose a PR to fix it.
