### ISSUE TITLE
axum opentelemetry

### ISSUE THREAD

**Issue by jayvdb** [flosse/rust-web-framework-comparison#148]
Decision at https://github.com/tokio-rs/axum/pull/769#issuecomment-1147360090 was that open telemetry can and thus should be third party , and so that has occurred at https://crates.io/crates/axum-tracing-opentelemetry , now present on https://github.com/tokio-rs/axum/blob/main/ECOSYSTEM.md

IMO this should means it gets a "yes", ideally with a hyperlink to the third party crate which provides it.

**Comment by flosse** [comment]
@jayvdb please open a PR for change requests. Thank you!
