### ISSUE TITLE
OpenHub links

### ISSUE THREAD

**Issue by jayvdb** [flosse/rust-web-framework-comparison#149]
I find OpenHub useful when doing comparisons of frameworks. 

e.g. https://openhub.net/p/actix-web vs  vs https://openhub.net/p/tide-rs
I just created https://openhub.net/p/axum and https://openhub.net/p/rocket-rs and https://openhub.net/p/warp-rs , so no stats there atm

Are you open to having OpenHub links added?

**Comment by flosse** [comment]
> Are you open to having OpenHub links added?

To be honest, I have never heard of this site before.
That is of course not a criterion :wink: 
What bothers me more is that I can't make sense of the information or recognize the added value.
Please re-open this issue if you continue to see added value in it and can explain it to me.
