### ISSUE TITLE
Rocket is active and up-to-date

### ISSUE THREAD

**Issue by mehrdad-drpc** [flosse/rust-web-framework-comparison#164]
Move Rocket to "[High-Level Server Frameworks](https://github.com/flosse/rust-web-framework-comparison#high-level-server-frameworks)" Section!

**Comment by flosse** [comment]
The latest stable release was Jul 14, 2022, so this is not up to date.
Even the last pre-release (v0.5.0-rc.3) was already 7 months ago.

**Comment by flosse** [comment]
Closed in favor of https://github.com/flosse/rust-web-framework-comparison/issues/154
