### ISSUE TITLE
I don't think yew is outdated

### ISSUE THREAD

**Issue by xfbs** [flosse/rust-web-framework-comparison#171]
Yew is quite popular, is being actively developed. I think it is currently one of the more popular Rust frontend web frameworks.

**Comment by dave-doty** [comment]
I agree, I don't know what criteria was used to decide what is outdated. Conversely, Iced is listed as not outdated for WASM despite Iced authors officially declaring that project abandoned:

https://discourse.iced.rs/t/is-publishing-to-web-working-and-fully-supported/515/2
https://github.com/iced-rs/iced_web

Similarly, is Sycamore really outdated? They have commits from a month ago: https://github.com/sycamore-rs/sycamore

**Comment by flosse** [comment]
@xfbs #154 is the right place to discuss here.
@dave-doty thanks for sharing your thoughts. Here are some of mine: https://github.com/flosse/rust-web-framework-comparison/issues/154#issuecomment-2282914640
