### ISSUE TITLE
Dynamic metrics?

### ISSUE THREAD

**Issue by ctjhoa** [flosse/rust-web-framework-comparison#77]
Hi,
Currently the "Comparison" part is static and should be updated manually.
What do you think about using something like https://shields.io/ to get all the data needed?

Example for `hyper`:
Markdown: `![Hyper license](https://img.shields.io/github/license/hyperium/hyper.svg)`
![Hyper license](https://img.shields.io/github/license/hyperium/hyper.svg)
Markdown: `![Hyper stars](https://img.shields.io/github/stars/hyperium/hyper.svg)`
![Hyper stars](https://img.shields.io/github/stars/hyperium/hyper.svg)

This could avoid maintenance cost but will slow down the loading of the `README`.
Keep in mind that those results are cached.

I'd be happy to do PRs on that.

**Comment by ctjhoa** [comment]
@flosse ?

**Comment by flosse** [comment]
@ctjhoa Go for it :)
