### ISSUE TITLE
Additional frontend frameworks

### ISSUE THREAD

**Issue by aidanhs** [flosse/rust-web-framework-comparison#89]
Just noting some new ones down I came across
 - https://github.com/Pauan/rust-dominator
 - ~~https://github.com/ivanceras/sauron~~ (already included)
 - https://github.com/axelf4/dumle

**Comment by aidanhs** [comment]
Sort of frontend, actually more general - https://github.com/redux-rs/redux-rs

**Comment by schell** [comment]
https://github.com/schell/mogwai 
:)

**Comment by flosse** [comment]
they are all included now.
