### ISSUE TITLE
The comparison of high-level backend frameworks could include stable Rust

### ISSUE THREAD

**Issue by anacrolix** [flosse/rust-web-framework-comparison#98]
The list of [high-level backend frameworks](https://github.com/flosse/rust-web-framework-comparison#high-level-frameworks) does not include a field for whether they work on stable Rust, like the [frontend-frameworks list](https://github.com/flosse/rust-web-framework-comparison#frontend-frameworks) does. I think this would be a good improvement.

**Comment by flosse** [comment]
That's a good idea ... do you like to create a PR? ;-)
