### ISSUE TITLE
Broken "rustwebapp" demo link

### ISSUE THREAD

**Issue by ethagnawl** [flosse/rust-web-framework-comparison#99]
The link to the [rustwebapp](https://github.com/superlogical/rustwebapp) demo is broken -- the owner seems to have closed their GH account. 

[This](https://github.com/kordless/rustwebapp) seems to be a fork of that project, though.

**Comment by flosse** [comment]
feel free to open a PR ;-)

**Comment by flosse** [comment]
> feel free to open a PR ;-)

still... please create a PR.
